language: ruby
rvm:
  - 2.5.0

services: 
  - postgresql

before_script:
  - gem install bundler:2.1.4
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate 

dist: trusty


script:
  - bundle exec rspec



