development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:e1c1d7a2079e7d3d9e8199c9a16753fc@soapfish.redistogo.com:9500/
  # channel_prefix: acebook_production
